<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Website\WebsiteController;
use Illuminate\Support\Facades\Auth;

Route::get('/', [WebsiteController::class, 'index']);

// Contractor Login Route
Route::get('/contractor/login', function () {
    return response()->file(public_path('contractor-login.html'));
})->name('contractor.login');

// Admin Panel Routes
Route::prefix('admin')->middleware('auth')->group(function () {
    Route::get('/', [AdminController::class, 'dashboard'])->name('admin.dashboard');
    Route::get('/home', [AdminController::class, 'home'])->name('admin.home');
    Route::get('/hero', [AdminController::class, 'hero'])->name('admin.hero');
    Route::get('/hero/create', [AdminController::class, 'createHero'])->name('admin.hero.create');
    Route::post('/hero', [AdminController::class, 'storeHero'])->name('admin.hero.store');
    Route::get('/hero/{id}/edit', [AdminController::class, 'editHero'])->name('admin.hero.edit');
    Route::put('/hero/{id}', [AdminController::class, 'updateHero'])->name('admin.hero.update');
    Route::delete('/hero/{id}', [AdminController::class, 'destroyHero'])->name('admin.hero.destroy');
    Route::patch('/hero/{id}/toggle', [AdminController::class, 'toggleHeroStatus'])->name('admin.hero.toggle');
    Route::get('/about', [AdminController::class, 'about'])->name('admin.about');
    Route::get('/about/create', [AdminController::class, 'createAbout'])->name('admin.about.create');
    Route::post('/about', [AdminController::class, 'storeAbout'])->name('admin.about.store');
    Route::get('/about/{id}/edit', [AdminController::class, 'editAbout'])->name('admin.about.edit');
    Route::put('/about/{id}', [AdminController::class, 'updateAbout'])->name('admin.about.update');
    Route::delete('/about/{id}', [AdminController::class, 'destroyAbout'])->name('admin.about.destroy');
    Route::patch('/about/{id}/toggle', [AdminController::class, 'toggleAboutStatus'])->name('admin.about.toggle');
    Route::get('/company-overview', [AdminController::class, 'companyOverview'])->name('admin.company-overview');
    Route::get('/company-overview/create', [AdminController::class, 'createCompanyOverview'])->name('admin.company-overview.create');
    Route::post('/company-overview', [AdminController::class, 'storeCompanyOverview'])->name('admin.company-overview.store');
    Route::get('/company-overview/{id}/edit', [AdminController::class, 'editCompanyOverview'])->name('admin.company-overview.edit');
    Route::put('/company-overview/{id}', [AdminController::class, 'updateCompanyOverview'])->name('admin.company-overview.update');
    Route::delete('/company-overview/{id}', [AdminController::class, 'destroyCompanyOverview'])->name('admin.company-overview.destroy');
    Route::patch('/company-overview/{id}/toggle', [AdminController::class, 'toggleCompanyOverviewStatus'])->name('admin.company-overview.toggle');
    Route::get('/leadership', [AdminController::class, 'leadership'])->name('admin.leadership');
    Route::get('/leadership/create', [AdminController::class, 'createLeadership'])->name('admin.leadership.create');
    Route::post('/leadership', [AdminController::class, 'storeLeadership'])->name('admin.leadership.store');
    Route::get('/leadership/{id}/edit', [AdminController::class, 'editLeadership'])->name('admin.leadership.edit');
    Route::put('/leadership/{id}', [AdminController::class, 'updateLeadership'])->name('admin.leadership.update');
    Route::delete('/leadership/{id}', [AdminController::class, 'destroyLeadership'])->name('admin.leadership.destroy');
    Route::patch('/leadership/{id}/toggle', [AdminController::class, 'toggleLeadershipStatus'])->name('admin.leadership.toggle');
    Route::get('/team', [AdminController::class, 'team'])->name('admin.team');
    Route::get('/team/create', [AdminController::class, 'createTeam'])->name('admin.team.create');
    Route::post('/team', [AdminController::class, 'storeTeam'])->name('admin.team.store');
    Route::get('/team/{id}/edit', [AdminController::class, 'editTeam'])->name('admin.team.edit');
    Route::put('/team/{id}', [AdminController::class, 'updateTeam'])->name('admin.team.update');
    Route::delete('/team/{id}', [AdminController::class, 'destroyTeam'])->name('admin.team.destroy');
    Route::patch('/team/{id}/toggle', [AdminController::class, 'toggleTeamStatus'])->name('admin.team.toggle');
    Route::get('/achievements', [AdminController::class, 'achievements'])->name('admin.achievements');
    Route::get('/achievements/create', [AdminController::class, 'createAchievement'])->name('admin.achievements.create');
    Route::post('/achievements', [AdminController::class, 'storeAchievement'])->name('admin.achievements.store');
    Route::get('/achievements/{id}/edit', [AdminController::class, 'editAchievement'])->name('admin.achievements.edit');
    Route::put('/achievements/{id}', [AdminController::class, 'updateAchievement'])->name('admin.achievements.update');
    Route::delete('/achievements/{id}', [AdminController::class, 'destroyAchievement'])->name('admin.achievements.destroy');
    Route::patch('/achievements/{id}/toggle', [AdminController::class, 'toggleAchievementStatus'])->name('admin.achievements.toggle');
    Route::get('/clients-feedback', [AdminController::class, 'clientsFeedback'])->name('admin.clients-feedback');
    Route::get('/clients-feedback/create', [AdminController::class, 'createClientFeedback'])->name('admin.clients-feedback.create');
    Route::post('/clients-feedback', [AdminController::class, 'storeClientFeedback'])->name('admin.clients-feedback.store');
    Route::get('/clients-feedback/{id}/edit', [AdminController::class, 'editClientFeedback'])->name('admin.clients-feedback.edit');
    Route::put('/clients-feedback/{id}', [AdminController::class, 'updateClientFeedback'])->name('admin.clients-feedback.update');
    Route::delete('/clients-feedback/{id}', [AdminController::class, 'destroyClientFeedback'])->name('admin.clients-feedback.destroy');
    Route::patch('/clients-feedback/{id}/toggle', [AdminController::class, 'toggleClientFeedbackStatus'])->name('admin.clients-feedback.toggle');
    Route::get('/partners', [AdminController::class, 'partners'])->name('admin.partners');
    Route::get('/partners/create', [AdminController::class, 'createPartner'])->name('admin.partners.create');
    Route::post('/partners', [AdminController::class, 'storePartner'])->name('admin.partners.store');
    Route::get('/partners/{id}/edit', [AdminController::class, 'editPartner'])->name('admin.partners.edit');
    Route::put('/partners/{id}', [AdminController::class, 'updatePartner'])->name('admin.partners.update');
    Route::delete('/partners/{id}', [AdminController::class, 'destroyPartner'])->name('admin.partners.destroy');
    Route::patch('/partners/{id}/toggle', [AdminController::class, 'togglePartnerStatus'])->name('admin.partners.toggle');
    Route::get('/why-choose', [AdminController::class, 'whyChoose'])->name('admin.why-choose');
    Route::get('/why-choose/create', [AdminController::class, 'createWhyChoose'])->name('admin.why-choose.create');
    Route::post('/why-choose', [AdminController::class, 'storeWhyChoose'])->name('admin.why-choose.store');
    Route::get('/why-choose/{id}/edit', [AdminController::class, 'editWhyChoose'])->name('admin.why-choose.edit');
    Route::put('/why-choose/{id}', [AdminController::class, 'updateWhyChoose'])->name('admin.why-choose.update');
    Route::delete('/why-choose/{id}', [AdminController::class, 'destroyWhyChoose'])->name('admin.why-choose.destroy');
    Route::patch('/why-choose/{id}/toggle', [AdminController::class, 'toggleWhyChooseStatus'])->name('admin.why-choose.toggle');
    Route::get('/featured-highlights', [AdminController::class, 'featuredHighlights'])->name('admin.featured-highlights');
    Route::get('/featured-highlights/create', [AdminController::class, 'createFeaturedHighlight'])->name('admin.featured-highlights.create');
    Route::post('/featured-highlights', [AdminController::class, 'storeFeaturedHighlight'])->name('admin.featured-highlights.store');
    Route::get('/featured-highlights/{id}/edit', [AdminController::class, 'editFeaturedHighlight'])->name('admin.featured-highlights.edit');
    Route::put('/featured-highlights/{id}', [AdminController::class, 'updateFeaturedHighlight'])->name('admin.featured-highlights.update');
    Route::delete('/featured-highlights/{id}', [AdminController::class, 'destroyFeaturedHighlight'])->name('admin.featured-highlights.destroy');
    Route::patch('/featured-highlights/{id}/toggle', [AdminController::class, 'toggleFeaturedHighlightStatus'])->name('admin.featured-highlights.toggle');
    Route::get('/latest-news', [AdminController::class, 'latestNews'])->name('admin.latest-news');
    Route::get('/latest-news/create', [AdminController::class, 'createLatestNews'])->name('admin.latest-news.create');
    Route::post('/latest-news', [AdminController::class, 'storeLatestNews'])->name('admin.latest-news.store');
    Route::get('/latest-news/{id}/edit', [AdminController::class, 'editLatestNews'])->name('admin.latest-news.edit');
    Route::put('/latest-news/{id}', [AdminController::class, 'updateLatestNews'])->name('admin.latest-news.update');
    Route::delete('/latest-news/{id}', [AdminController::class, 'destroyLatestNews'])->name('admin.latest-news.destroy');
    Route::patch('/latest-news/{id}/toggle', [AdminController::class, 'toggleLatestNewsStatus'])->name('admin.latest-news.toggle');
    Route::get('/business-hours', [AdminController::class, 'businessHours'])->name('admin.business-hours');
    Route::get('/business-hours/create', [AdminController::class, 'createBusinessHours'])->name('admin.business-hours.create');
    Route::post('/business-hours', [AdminController::class, 'storeBusinessHours'])->name('admin.business-hours.store');
    Route::get('/business-hours/{id}/edit', [AdminController::class, 'editBusinessHours'])->name('admin.business-hours.edit');
    Route::put('/business-hours/{id}', [AdminController::class, 'updateBusinessHours'])->name('admin.business-hours.update');
    Route::delete('/business-hours/{id}', [AdminController::class, 'destroyBusinessHours'])->name('admin.business-hours.destroy');
    Route::patch('/business-hours/{id}/toggle', [AdminController::class, 'toggleBusinessHoursStatus'])->name('admin.business-hours.toggle');
    Route::get('/careers', [AdminController::class, 'careers'])->name('admin.careers');
    Route::get('/careers/create', [AdminController::class, 'createCareer'])->name('admin.careers.create');
    Route::post('/careers', [AdminController::class, 'storeCareer'])->name('admin.careers.store');
    Route::get('/careers/{id}/edit', [AdminController::class, 'editCareer'])->name('admin.careers.edit');
    Route::put('/careers/{id}', [AdminController::class, 'updateCareer'])->name('admin.careers.update');
    Route::delete('/careers/{id}', [AdminController::class, 'destroyCareer'])->name('admin.careers.destroy');
    Route::patch('/careers/{id}/toggle', [AdminController::class, 'toggleCareerStatus'])->name('admin.careers.toggle');
    Route::get('/mentorship', [AdminController::class, 'mentorship'])->name('admin.mentorship');
    Route::get('/mentorship/create', [AdminController::class, 'createMentorship'])->name('admin.mentorship.create');
    Route::post('/mentorship', [AdminController::class, 'storeMentorship'])->name('admin.mentorship.store');
    Route::get('/mentorship/{id}/edit', [AdminController::class, 'editMentorship'])->name('admin.mentorship.edit');
    Route::put('/mentorship/{id}', [AdminController::class, 'updateMentorship'])->name('admin.mentorship.update');
    Route::delete('/mentorship/{id}', [AdminController::class, 'destroyMentorship'])->name('admin.mentorship.destroy');
    Route::patch('/mentorship/{id}/toggle', [AdminController::class, 'toggleMentorshipStatus'])->name('admin.mentorship.toggle');
    Route::get('/expertise', [AdminController::class, 'expertise'])->name('admin.expertise');
    Route::get('/expertise/create', [AdminController::class, 'createExpertise'])->name('admin.expertise.create');
    Route::post('/expertise', [AdminController::class, 'storeExpertise'])->name('admin.expertise.store');
    Route::get('/expertise/{id}/edit', [AdminController::class, 'editExpertise'])->name('admin.expertise.edit');
    Route::put('/expertise/{id}', [AdminController::class, 'updateExpertise'])->name('admin.expertise.update');
    Route::delete('/expertise/{id}', [AdminController::class, 'destroyExpertise'])->name('admin.expertise.destroy');
    Route::patch('/expertise/{id}/toggle', [AdminController::class, 'toggleExpertiseStatus'])->name('admin.expertise.toggle');
    Route::get('/technical-specializations', [AdminController::class, 'technicalSpecializations'])->name('admin.technical-specializations');
    Route::get('/technical-specializations/create', [AdminController::class, 'createTechnicalSpecialization'])->name('admin.technical-specializations.create');
    Route::post('/technical-specializations', [AdminController::class, 'storeTechnicalSpecialization'])->name('admin.technical-specializations.store');
    Route::get('/technical-specializations/{id}/edit', [AdminController::class, 'editTechnicalSpecialization'])->name('admin.technical-specializations.edit');
    Route::put('/technical-specializations/{id}', [AdminController::class, 'updateTechnicalSpecialization'])->name('admin.technical-specializations.update');
    Route::delete('/technical-specializations/{id}', [AdminController::class, 'destroyTechnicalSpecialization'])->name('admin.technical-specializations.destroy');
    Route::patch('/technical-specializations/{id}/toggle', [AdminController::class, 'toggleTechnicalSpecializationStatus'])->name('admin.technical-specializations.toggle');
    Route::get('/certifications', [AdminController::class, 'certifications'])->name('admin.certifications');
    Route::get('/certifications/create', [AdminController::class, 'createCertification'])->name('admin.certifications.create');
    Route::post('/certifications', [AdminController::class, 'storeCertification'])->name('admin.certifications.store');
    Route::get('/certifications/{id}/edit', [AdminController::class, 'editCertification'])->name('admin.certifications.edit');
    Route::put('/certifications/{id}', [AdminController::class, 'updateCertification'])->name('admin.certifications.update');
    Route::delete('/certifications/{id}', [AdminController::class, 'destroyCertification'])->name('admin.certifications.destroy');
    Route::patch('/certifications/{id}/toggle', [AdminController::class, 'toggleCertificationStatus'])->name('admin.certifications.toggle');
    Route::get('/memberships', [AdminController::class, 'memberships'])->name('admin.memberships');
    Route::get('/memberships/create', [AdminController::class, 'createMembership'])->name('admin.memberships.create');
    Route::post('/memberships', [AdminController::class, 'storeMembership'])->name('admin.memberships.store');
    Route::get('/memberships/{id}/edit', [AdminController::class, 'editMembership'])->name('admin.memberships.edit');
    Route::put('/memberships/{id}', [AdminController::class, 'updateMembership'])->name('admin.memberships.update');
    Route::delete('/memberships/{id}', [AdminController::class, 'destroyMembership'])->name('admin.memberships.destroy');
    Route::patch('/memberships/{id}/toggle', [AdminController::class, 'toggleMembershipStatus'])->name('admin.memberships.toggle');
    Route::get('/job-applications', [AdminController::class, 'jobApplications'])->name('admin.job-applications');
    Route::get('/job-applications/{id}', [AdminController::class, 'showJobApplication'])->name('admin.job-applications.show');
    Route::patch('/job-applications/{id}/status', [AdminController::class, 'updateJobApplicationStatus'])->name('admin.job-applications.update-status');
    Route::post('/job-applications/{id}/reply', [AdminController::class, 'replyToJobApplication'])->name('admin.job-applications.reply');
    Route::get('/job-applications/{id}/download-resume', [AdminController::class, 'downloadResume'])->name('admin.job-applications.download-resume');
    Route::delete('/job-applications/{id}', [AdminController::class, 'destroyJobApplication'])->name('admin.job-applications.destroy');
    Route::get('/mentorship', [AdminController::class, 'mentorship'])->name('admin.mentorship');
    Route::get('/expertise', [AdminController::class, 'expertise'])->name('admin.expertise');
    Route::get('/technical-specializations', [AdminController::class, 'technicalSpecializations'])->name('admin.technical-specializations');
    Route::get('/certifications', [AdminController::class, 'certifications'])->name('admin.certifications');
    Route::get('/featured-highlights', [AdminController::class, 'featuredHighlights'])->name('admin.featured-highlights');
    Route::get('/latest-news', [AdminController::class, 'latestNews'])->name('admin.latest-news');
    Route::get('/business-hours', [AdminController::class, 'businessHours'])->name('admin.business-hours');
    Route::get('/careers', [AdminController::class, 'careers'])->name('admin.careers');
    Route::get('/contact-form', [AdminController::class, 'contactForm'])->name('admin.contact-form');
    Route::get('/get-in-touch', [AdminController::class, 'getInTouch'])->name('admin.get-in-touch');
    Route::get('/get-in-touch/create', [AdminController::class, 'createGetInTouch'])->name('admin.get-in-touch.create');
    Route::post('/get-in-touch', [AdminController::class, 'storeGetInTouch'])->name('admin.get-in-touch.store');
    Route::get('/get-in-touch/{id}/edit', [AdminController::class, 'editGetInTouch'])->name('admin.get-in-touch.edit');
    Route::put('/get-in-touch/{id}', [AdminController::class, 'updateGetInTouch'])->name('admin.get-in-touch.update');
    Route::delete('/get-in-touch/{id}', [AdminController::class, 'destroyGetInTouch'])->name('admin.get-in-touch.destroy');
    Route::patch('/get-in-touch/{id}/toggle', [AdminController::class, 'toggleGetInTouchStatus'])->name('admin.get-in-touch.toggle');
    Route::get('/projects', [AdminController::class, 'projects'])->name('admin.projects');
    Route::get('/csr', [AdminController::class, 'csr'])->name('admin.csr');
    Route::get('/contact', [AdminController::class, 'contact'])->name('admin.contact');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
